import { parseRawDnaText, decompressGenomicBuffer, normalizeChromosome } from '../src/services/dnaParser';
import { YDnaPredictorV2 } from '../src/services/yDnaPredictorV2';
import { matchPhyloTreeBuild17, refineMtdnaWithBuild17 } from '../src/services/phylotreeMtdnaEngine';
import { gzipSync } from 'fflate';
import * as fs from 'fs';
import * as path from 'path';

console.log('=== TEST 1: AncestryDNA Chromosome Mapping (Chr 24, 25, 26) ===');
const sampleAncestry = `
# AncestryDNA raw data download
# This file was generated by AncestryDNA
rsid	chromosome	position	allele1	allele2
rs9306841	24	13533801	T	T
rs1234567	25	1000000	A	G
rs2853499	26	7028	C	C
`;

const parsedAncestry = parseRawDnaText(sampleAncestry);
console.log('Detected Format:', parsedAncestry.format);
console.log('Detected Build:', parsedAncestry.build);
console.log('Y SNPs Count:', parsedAncestry.yDnaSnps);
console.log('MT SNPs Count:', parsedAncestry.mtDnaSnps);
console.log('Chr 25 locus in MT?', parsedAncestry.snpByPosition['mt:1000000'] !== undefined ? 'FAIL (Chr 25 in MT)' : 'PASS (Chr 25 NOT in MT)');
console.log('Chr 25 locus in X?', parsedAncestry.snpByPosition['x:1000000'] !== undefined ? 'PASS (Chr 25 in X)' : 'FAIL');
console.log('Chr 26 locus in MT?', parsedAncestry.snpByPosition['mt:7028'] === 'C' ? 'PASS (Chr 26 in MT)' : 'FAIL');

console.log('\n=== TEST 2: Haploid Quality Control (Heterozygous Filtering) ===');
const sampleHaploidNoise = `
rs9306841	Y	13533801	A	G
rs2853499	MT	7028	C	T
rs9786481	Y	14896238	C	C
`;
const parsedHaploid = parseRawDnaText(sampleHaploidNoise);
console.log('Y heterozygous (A/G) status:', parsedHaploid.snpByRsid['rs9306841'] === '--' ? 'PASS (Rejected as --)' : 'FAIL');
console.log('MT heterozygous (C/T) status:', parsedHaploid.snpByRsid['rs2853499'] === '--' ? 'PASS (Rejected as --)' : 'FAIL');
console.log('Y homozygous (C/C) normalized:', parsedHaploid.snpByRsid['rs9786481'] === 'C' ? 'PASS (Normalized to C)' : 'FAIL');

console.log('\n=== TEST 3: GZIP Binary Buffer Decompression ===');
const plainSnippet = 'rs9306841\tY\t13533801\tT\nrs9786481\tY\t14896238\tC\n';
const gzipped = gzipSync(new TextEncoder().encode(plainSnippet));
const decompressed = decompressGenomicBuffer(gzipped);
const decoded = new TextDecoder('utf-8').decode(decompressed);
console.log('GZIP Decompression check:', decoded === plainSnippet ? 'PASS (Identical text)' : 'FAIL');

console.log('\n=== TEST 4: Phase 2 Y-DNA Traversal Engine (ISOGG Tree) ===');
const phyloPath = path.join(__dirname, '../public/data/y_phylotree.json');
if (fs.existsSync(phyloPath)) {
  const yPhyloDataset = JSON.parse(fs.readFileSync(phyloPath, 'utf-8'));
  const predictor = new YDnaPredictorV2(yPhyloDataset);

  // Test with an R1b sample carrying M269, L21, etc.
  const r1bInput = {
    snpByRsid: {
      'm168': 'T',
      'm89': 'C',
      'm9': 'G',
      'm45': 'A',
      'm207': 'A',
      'm173': 'A',
      'm343': 'C',
      'm269': 'C',
      'l21': 'C'
    },
    snpByPosition: {
      'y:13533801': 'T'
    }
  };

  const res = predictor.predict(r1bInput);
  console.log('Terminal Haplogroup:', res.terminalHaplogroup);
  console.log('Confidence:', res.confidence + '%');
  console.log('Coverage:', res.coverage + '%');
  console.log('Derived Count:', res.derivedSnpCount);
  console.log('Path:', res.path.slice(-5).join(' -> '));
  console.log('Derived Markers sample:', res.derivedMarkers.slice(0, 3).map(m => `${m.name}(${m.allele})`));
  console.log('Pruned Sibling Branches count:', res.rejectedBranches.length);

  if (res.terminalHaplogroup.includes('R') || res.derivedSnpCount > 0) {
    console.log('Phase 2 Engine: PASS');
  } else {
    console.log('Phase 2 Engine: FAIL');
  }
} else {
  console.log('y_phylotree.json not found at', phyloPath);
}

console.log('\n=== ALL UPGRADE TESTS COMPLETED ===');
